### ISSUE TITLE
Lack of methods for importing brats data in DataGenerator code？

### ISSUE THREAD

**Issue by liaochuanlin** [RL4M/PCRLv2#8]
pcrlv2_brats_finetune
Traceback (most recent call last):
  File "/home/lcl/PCRLv2/main.py", line 46, in <module>
    data_loader = get_dataloader(args)
  File "/home/lcl/PCRLv2/main.py", line 17, in get_dataloader
    dataloader = getattr(generator, loader_name)()
AttributeError: 'DataGenerator' object has no attribute 'pcrlv2_brats_finetune'

**Comment by joangog** [comment]
You have to git checkout to the "finetune" branch of the repo.
